service: poc

frameworkVersion: "2"

custom:
  maintainer: three
  description: "Serverless application POC"
  mgmt_region: us-east-1

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: ${self:custom.mgmt_region}
  timeout: 30 # this is because the lambdas are attached to api gateway
  logRetentionInDays: 14
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
  stackTags:
    DEPLOYMENT_TOOL: sls
    MAINTAINER: ${self:custom.maintainer}
    DESCRIPTION: ${self:custom.description}
    APPLICATION: poc
  apiKeys:
    - ${self:service}-api-key
  logs:
    restApi: true

package:
  individually: true

functions:
  create_s3_bucket:
    description: Create AWS S3 bucket
    handler: create_s3_bucket/handler.create_s3_bucket
    events:
      - http:
          path: ${self:service}/create_s3_bucket
          method: POST
          private: true
    memorySize: 128
    environment:
      LOG_LEVEL: DEBUG
    package:
      exclude:
        - "**"
      include:
        - create_s3_bucket/handler.py

  upload_to_s3_bucket:
    description: Generate presigned URL for uploading object to given AWS S3 bucket
    handler: upload_to_s3_bucket/handler.upload_to_s3_bucket
    events:
      - http:
          path: ${self:service}/upload_to_s3_bucket
          method: POST
          private: true
    memorySize: 128
    environment:
      LOG_LEVEL: DEBUG
    package:
      exclude:
        - "**"
      include:
        - upload_to_s3_bucket/handler.py

  list_s3_bucket:
    description: List files in given AWS S3 bucket
    handler: list_s3_bucket/handler.list_s3_bucket
    events:
      - http:
          path: ${self:service}/list_s3_bucket/{bucket_name}
          method: GET
          private: true
    memorySize: 128
    environment:
      LOG_LEVEL: DEBUG
    package:
      exclude:
        - "**"
      include:
        - list_s3_bucket/handler.py

plugins:
  - serverless-offline
